### ISSUE TITLE
Developer documentation overhaul - Bizdev/foundation initative

### ISSUE THREAD

**Issue by ertemann** [SecretFoundation/docs#30]
This issue is used to keep a detailed overview of the work done on the Bizdev developer documentation initiative proposal which was laid out in [this](https://forum.scrt.network/t/bizdev-committee-initiative-proposal-q1-developer-documentation/5118/12) forum post.

### Summary:

The developer documentation is slightly outdated and incomplete. In order to improve the onboarding process of new developers and developers from other ecosystems @dylanschultzie proposes to follow this 6 step approach. These 6 steps are divided among 3 short and 3 long term goals. The first 3 steps are covered within the current proposal, the long term steps are still open for grants or a next proposal.

### Steps Short term:

- [x] 1.     Do quick repairs on the docs - make sure links work, nothing is immediately incorrect, etc.

Some of this has been done already [1](https://github.com/SecretFoundation/docs/pull/22) , [2](https://github.com/SecretFoundation/docs/pull/20) , but it’s clear that more attention needs done from a quick pass perspective. This is intended as a stopgap solution. Get in, so that while working on 2, incoming developers are in a better state.

#31 used to track this step.

- [x] 2.     Go through the active dev docs

This is the bulk of the short-term work. It will include going through every single step on all tutorials provided on https://docs.scrt.network/  and [Figment Learn | Secret ](https://learn.figment.io/protocols/secret), including fixing and improving upon them. Note that I don’t think figment currently accepts direct fixes, so this will be more involved.

I believe doing every tutorial is paramount to a job well done here, as reading over and reviewing the documentation isn’t the same as executing every command provided.

- [x] 3.     Do a thorough analysis of the docs

Finally, this will include comparing the documentation against source documentation, such as gaiacli. With Supernova, much of the cli has been updated and so the documentation is no longer correct. This documentation either needs to be reviewed, re-written, or purged completely. For much of the documentation I don’t see a ton of benefit to keeping what amounts to a copy & paste of the source docs, with gaiacli replaced with secretcli.

### Steps Long term:

- [ ] 4.     Coordinate internal Secret tooling

There are a ton of tools that have been built around Secret that aren’t in a unified location for developers to quickly access. These should be coordinated, and documented. Explain how to use them, why to use them, etc. As an example, why is [Griptape](https://griptapejs.com/) not referenced?

- [ ] 5.    Create a “How to Port your dApp from Terra to Secret”

We need more developers. Why not invite those from Terra and other ecosystems to port their dApps, but private?

- [ ] 6.    Align Secret dev docs with external cosmwasm dev docs

### Timeline
The following is a rough expectation of timeline, assuming the proposal goes through the week of January 3rd, 2022:

1. The initial pass will take up to 2 weeks, concluding January 15th
2. The thorough dev docs will take roughly 2 months, concluding around March 15th
3. The final pass should take another 1-2 weeks, concluding by April 1st

**Comment by dylanschultzie** [comment]
Phase 3:
- https://github.com/SecretFoundation/docs/pull/45#discussion_r785074953

**Comment by ertemann** [comment]
Lets close this in favor of the current overhaul? make sure the same goals we set here are still met in the new overhaul

**Comment by StoicNorth** [comment]
@ertemann Closing now that we have the new doc issues.
